version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run coverage
      - codecov/upload:
          file: coverage/*.json